# Generated by Django 4.2.2 on 2023-06-30 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=55)),
                ('cus_ph', models.CharField(max_length=12)),
                ('cus_email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Wedding', 'Wedding'), ('Conference', 'Conference'), ('Concert', 'Concert'), ('Corporate', 'Corporate'), ('Other', 'Other')], max_length=50)),
                ('booking_startdate', models.DateField()),
                ('booking_enddate', models.DateField()),
                ('booking_starttime', models.TimeField()),
                ('booking_endtime', models.TimeField()),
                ('ticket_type', models.CharField(choices=[('Basic', 'Basic Plan'), ('Standard', 'Standard Plan'), ('VIP', 'VIP PLAN')], max_length=50)),
                ('ticket_quantity', models.PositiveIntegerField(default=0)),
                ('ticket_price', models.DecimalField(decimal_places=2, default=0.00, max_digits=10)),
                ('price_per_ticket', models.DecimalField(decimal_places=2, default=0.00, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.00, max_digits=10)),
                ('promo_code', models.CharField(blank=True, max_length=50, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.00, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Credit Card', 'Credit Card'), ('PayPal', 'PayPal'), ('Bank Transfer', 'Bank Transfer')], max_length=50)),
                ('booking_date', models.DateField()),
                ('booked_on', models.DateField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.event')),
            ],
        ),
    ]
