# Generated by Django 5.2.1 on 2025-05-28 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_auto_20250512_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_enddate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_endtime',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_startdate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_starttime',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='booking',
            name='city',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='country',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='cus_email',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('PayPal', 'PayPal'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash')], default='Credit Card', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='price_per_ticket',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_type',
            field=models.CharField(choices=[('Basic', 'Basic Plan'), ('Standard', 'Standard Plan'), ('VIP', 'VIP PLAN')], default='Basic', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='type',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Conference', 'Conference'), ('Concert', 'Concert'), ('Corporate', 'Corporate'), ('Other', 'Other')], default='Wedding', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cus_name',
            field=models.CharField(default='unknown', max_length=55),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cus_ph',
            field=models.CharField(default='unknown', max_length=12),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
