# Generated by Django 5.2.1 on 2025-05-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_remove_booking_booking_date_booking_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_enddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_endtime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_startdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_starttime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cus_email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cus_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cus_ph',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='ticket_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='ticket_type',
            field=models.CharField(choices=[('Basic', 'Basic Plan'), ('Standard', 'Standard Plan'), ('VIP', 'VIP PLAN')], max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='type',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Conference', 'Conference'), ('Concert', 'Concert'), ('Corporate', 'Corporate'), ('Other', 'Other')], max_length=50),
        ),
    ]
