# Generated by Django 5.2.1 on 2025-05-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0006_alter_booking_id_alter_event_id_alter_eventimage_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booked_on',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cus_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cus_ph',
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='admin@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='message',
            field=models.TextField(default='No message provided'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
