# Generated by Django 5.2.1 on 2025-05-28 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0006_alter_booking_address_alter_booking_city_and_more'),
        ('eventapp', '0007_contactmessage_remove_booking_booked_on_and_more'),
    ]

    operations = [
    ]
