# Generated by Django 5.2.1 on 2025-05-28 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0008_merge_20250528_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='message',
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='img',
            field=models.ImageField(default='pic/default.jpg', upload_to='pic'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='desc',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(default='pic/default.jpg', upload_to='pic'),
        ),
    ]
